<?php
/**
 * Title: Architecture flow
 * Slug: rismor/architecture-flow
 * Categories: rismor-content
 * Description: Editable technical architecture section using native groups and labels.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","className":"rismor-architecture-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-architecture-section" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:columns {"align":"wide","verticalAlignment":"top","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns alignwide are-vertically-aligned-top"><!-- wp:column {"width":"34%"} --><div class="wp-block-column" style="flex-basis:34%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">How it fits together</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Architecture you can explain on one page.</h2><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">Use this pattern to turn a complex solution into a clear sequence of systems, controls and outcomes.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"width":"66%"} --><div class="wp-block-column" style="flex-basis:66%"><!-- wp:group {"className":"rismor-flow-diagram","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-flow-diagram"><!-- wp:group {"className":"rismor-flow-step","layout":{"type":"flex","flexWrap":"nowrap"}} --><div class="wp-block-group rismor-flow-step"><!-- wp:paragraph {"className":"rismor-flow-index"} --><p class="rismor-flow-index">01</p><!-- /wp:paragraph --><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Identity</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Users authenticate through a controlled identity plane with policy applied before access is granted.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-flow-step","layout":{"type":"flex","flexWrap":"nowrap"}} --><div class="wp-block-group rismor-flow-step"><!-- wp:paragraph {"className":"rismor-flow-index"} --><p class="rismor-flow-index">02</p><!-- /wp:paragraph --><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Protected access</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Applications and services stay private while secure access is brokered through policy and device context.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-flow-step","layout":{"type":"flex","flexWrap":"nowrap"}} --><div class="wp-block-group rismor-flow-step"><!-- wp:paragraph {"className":"rismor-flow-index"} --><p class="rismor-flow-index">03</p><!-- /wp:paragraph --><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Workloads</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Compute, storage and applications are separated into manageable services with clear ownership and recovery paths.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-flow-step","layout":{"type":"flex","flexWrap":"nowrap"}} --><div class="wp-block-group rismor-flow-step"><!-- wp:paragraph {"className":"rismor-flow-index"} --><p class="rismor-flow-index">04</p><!-- /wp:paragraph --><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Recovery</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Backup and recovery are designed as part of the system, not bolted on after the architecture is finished.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->