<?php
/**
 * Title: Case study challenge and solution
 * Slug: rismor/case-study-challenge-solution
 * Categories: rismor-projects
 * Description: Alternating project narrative with challenge, solution and editable technical note.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","className":"rismor-case-narrative","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide rismor-case-narrative"><!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns"><!-- wp:column {"width":"28%"} --><div class="wp-block-column" style="flex-basis:28%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">01 · Challenge</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"2xl"} --><h2 class="wp-block-heading has-2-xl-font-size">The obvious solution created the wrong exposure.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column {"width":"72%"} --><div class="wp-block-column" style="flex-basis:72%"><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">Explain the operational problem, why the easy answer was unsuitable, and the constraints the solution needed to respect.</p><!-- /wp:paragraph --><!-- wp:group {"className":"rismor-tech-note","backgroundColor":"mist","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","right":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40"}}},"layout":{"type":"constrained"}} --><div class="wp-block-group rismor-tech-note has-mist-background-color has-background" style="padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--40)"><!-- wp:paragraph {"className":"rismor-eyebrow"} --><p class="rismor-eyebrow">Design constraint</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Keep internal services private while still giving authorised external users a simple browser-based route into the platform.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:separator {"style":{"spacing":{"margin":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}}} --><hr class="wp-block-separator has-alpha-channel-opacity" style="margin-top:var(--wp--preset--spacing--60);margin-bottom:var(--wp--preset--spacing--60)"/><!-- /wp:separator -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns"><!-- wp:column {"width":"28%"} --><div class="wp-block-column" style="flex-basis:28%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">02 · Solution</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"2xl"} --><h2 class="wp-block-heading has-2-xl-font-size">Separate access from the application itself.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column {"width":"72%"} --><div class="wp-block-column" style="flex-basis:72%"><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">Describe the architectural decision in terms a buyer can understand, then use the Architecture Flow pattern alongside it when the technical detail matters.</p><!-- /wp:paragraph --><!-- wp:list --><ul class="wp-block-list"><li>Private application services</li><li>Identity-provider authentication</li><li>Policy-enforced access</li><li>Repeatable deployments and documented recovery</li></ul><!-- /wp:list --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group --></div><!-- /wp:group -->