<?php
/**
 * Title: Case study opening
 * Slug: rismor/case-study-opening
 * Categories: rismor-projects
 * Description: Large project introduction with brief, outcome and technology rail.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","className":"rismor-case-opening","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-case-opening" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Project · Platform engineering</p><!-- /wp:paragraph --><!-- wp:heading {"level":1,"fontSize":"4xl"} --><h1 class="wp-block-heading has-4-xl-font-size">A secure sandbox where ideas can become working software.</h1><!-- /wp:heading -->
<!-- wp:columns {"className":"rismor-case-meta","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"},"blockGap":{"left":"var:preset|spacing|50"}}}} --><div class="wp-block-columns rismor-case-meta" style="margin-top:var(--wp--preset--spacing--50)"><!-- wp:column {"width":"50%"} --><div class="wp-block-column" style="flex-basis:50%"><!-- wp:paragraph {"className":"rismor-eyebrow"} --><p class="rismor-eyebrow">The brief</p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">Create a safe, repeatable application environment that non-specialist users can access without exposing internal services directly to the internet.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"width":"30%"} --><div class="wp-block-column" style="flex-basis:30%"><!-- wp:paragraph {"className":"rismor-eyebrow"} --><p class="rismor-eyebrow">Outcome</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Private access<br>Repeatable deployments<br>Persistent data<br>Clear operational model</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"width":"20%"} --><div class="wp-block-column" style="flex-basis:20%"><!-- wp:paragraph {"className":"rismor-eyebrow"} --><p class="rismor-eyebrow">Technology</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Docker<br>PostgreSQL<br>Cloudflare<br>Microsoft Entra</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:cover {"dimRatio":0,"overlayColor":"mist","minHeight":620,"align":"wide","className":"rismor-case-hero-media","style":{"spacing":{"margin":{"top":"var:preset|spacing|60"}}}} --><div class="wp-block-cover alignwide rismor-case-hero-media" style="margin-top:var(--wp--preset--spacing--60);min-height:620px"><span aria-hidden="true" class="wp-block-cover__background has-mist-background-color has-background-dim-0 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","className":"rismor-eyebrow","textColor":"slate"} --><p class="has-text-align-center rismor-eyebrow has-slate-color has-text-color">Replace this editable Cover block with project photography, interface capture or architecture artwork</p><!-- /wp:paragraph --></div></div><!-- /wp:cover --></div><!-- /wp:group --></div><!-- /wp:group -->