<?php
/**
 * Title: Contact split
 * Slug: rismor/contact-split
 * Categories: rismor-conversion
 * Description: Standalone enquiry section with direct contact routes and a form-ready content area.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"ink","textColor":"white","className":"rismor-contact-split","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-contact-split has-white-color has-ink-background-color has-text-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns alignwide"><!-- wp:column {"width":"52%"} --><div class="wp-block-column" style="flex-basis:52%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Talk to us</p><!-- /wp:paragraph --><!-- wp:heading {"textColor":"white","fontSize":"4xl"} --><h2 class="wp-block-heading has-white-color has-text-color has-4-xl-font-size">Tell us what is getting in the way.</h2><!-- /wp:heading --><!-- wp:paragraph {"textColor":"white","fontSize":"lg"} --><p class="has-white-color has-text-color has-lg-font-size">Start with the problem, the outcome you need or the thing nobody has managed to make behave yet.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"width":"48%","className":"rismor-contact-options"} --><div class="wp-block-column rismor-contact-options" style="flex-basis:48%"><!-- wp:group {"className":"rismor-contact-option","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-contact-option"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Email</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"textColor":"white","fontSize":"2xl"} --><h3 class="wp-block-heading has-white-color has-text-color has-2-xl-font-size"><a href="mailto:hello@example.com">hello@example.com</a></h3><!-- /wp:heading --><!-- wp:paragraph {"textColor":"slate"} --><p class="has-slate-color has-text-color">Replace with the correct enquiry address.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-contact-option","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-contact-option"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Phone</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"textColor":"white","fontSize":"2xl"} --><h3 class="wp-block-heading has-white-color has-text-color has-2-xl-font-size"><a href="tel:+440000000000">+44 (0) 0000 000000</a></h3><!-- /wp:heading --><!-- wp:paragraph {"textColor":"slate"} --><p class="has-slate-color has-text-color">Replace with the correct number and availability.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-contact-option","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-contact-option"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Form integration</p><!-- /wp:paragraph --><!-- wp:paragraph {"textColor":"white"} --><p class="has-white-color has-text-color">Insert the form block provided by your preferred forms plugin here. The theme deliberately does not hard-code a forms dependency.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->