<?php
/**
 * Title: FAQ with contact rail
 * Slug: rismor/faq-contact
 * Categories: rismor-conversion
 * Description: Native Details block FAQ paired with a strong enquiry rail.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","className":"rismor-faq-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-faq-section" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns alignwide"><!-- wp:column {"width":"34%","className":"rismor-faq-intro"} --><div class="wp-block-column rismor-faq-intro" style="flex-basis:34%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Common questions</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">The useful questions before we start.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Keep the answers concise. If the question needs a technical essay, it probably belongs in an insight article instead.</p><!-- /wp:paragraph --><!-- wp:group {"backgroundColor":"ink","textColor":"white","className":"rismor-contact-rail","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","right":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50"},"margin":{"top":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} --><div class="wp-block-group rismor-contact-rail has-white-color has-ink-background-color has-text-color has-background" style="margin-top:var(--wp--preset--spacing--50);padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--50)"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Still not sure?</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"textColor":"white","fontSize":"2xl"} --><h3 class="wp-block-heading has-white-color has-text-color has-2-xl-font-size">Tell us what you are trying to achieve.</h3><!-- /wp:heading --><!-- wp:paragraph {"textColor":"white"} --><p class="has-white-color has-text-color">A useful first conversation is usually enough to establish whether we can help.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"cyan","textColor":"ink","className":"is-style-rismor-arrow"} --><div class="wp-block-button is-style-rismor-arrow"><a class="wp-block-button__link has-ink-color has-cyan-background-color has-text-color has-background wp-element-button" href="#">Talk to Rismor</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column {"width":"66%","className":"rismor-faq-list"} --><div class="wp-block-column rismor-faq-list" style="flex-basis:66%"><!-- wp:details --><details class="wp-block-details"><summary>Do you only work with businesses that need ongoing support?</summary><!-- wp:paragraph --><p>No. The theme ships with placeholder copy: replace this with the actual commercial model, including projects, retainers or one-off consultancy where appropriate.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details --><details class="wp-block-details"><summary>Can you work alongside an existing IT team or supplier?</summary><!-- wp:paragraph --><p>Use this answer to explain how Rismor can complement internal teams, specialist suppliers or existing managed-service arrangements.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details --><details class="wp-block-details"><summary>Do you provide fixed-price projects?</summary><!-- wp:paragraph --><p>Explain when fixed scope is appropriate and when discovery or time-based consultancy produces a better outcome.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details --><details class="wp-block-details"><summary>What size organisations do you work with?</summary><!-- wp:paragraph --><p>Replace with the real target-market answer rather than inventing a range simply to fill the pattern.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details --><details class="wp-block-details"><summary>Where are services delivered?</summary><!-- wp:paragraph --><p>Use this answer for UK coverage, remote delivery and any on-site arrangements that genuinely apply.</p><!-- /wp:paragraph --></details><!-- /wp:details --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->