<?php
/**
 * Title: Editorial dark footer
 * Slug: rismor/footer-editorial
 * Categories: rismor-navigation
 * Description: Large dark footer with conversion message, navigation and company details.
 * Block Types: core/template-part/footer
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"ink","textColor":"white","className":"rismor-footer-editorial","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-footer-editorial has-white-color has-ink-background-color has-text-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--50)"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:columns {"verticalAlignment":"bottom","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns are-vertically-aligned-bottom"><!-- wp:column {"verticalAlignment":"bottom","width":"64%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:64%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Start a conversation</p><!-- /wp:paragraph --><!-- wp:heading {"textColor":"white","fontSize":"4xl"} --><h2 class="wp-block-heading has-white-color has-text-color has-4-xl-font-size">Got something difficult?</h2><!-- /wp:heading --><!-- wp:paragraph {"textColor":"cyan","fontSize":"3xl"} --><p class="has-cyan-color has-text-color has-3-xl-font-size">Good.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"bottom","width":"36%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:36%"><!-- wp:paragraph {"textColor":"white","fontSize":"lg"} --><p class="has-white-color has-text-color has-lg-font-size">Tell us what you are trying to achieve and where the current technology is getting in the way.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"cyan","textColor":"ink","className":"is-style-rismor-arrow"} --><div class="wp-block-button is-style-rismor-arrow"><a class="wp-block-button__link has-ink-color has-cyan-background-color has-text-color has-background wp-element-button" href="#">Talk to Rismor</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:separator {"backgroundColor":"slate","style":{"spacing":{"margin":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|50"}}}} --><hr class="wp-block-separator has-text-color has-slate-color has-alpha-channel-opacity has-slate-background-color has-background" style="margin-top:var(--wp--preset--spacing--60);margin-bottom:var(--wp--preset--spacing--50)"/><!-- /wp:separator -->
<!-- wp:columns {"className":"rismor-footer-grid"} --><div class="wp-block-columns rismor-footer-grid"><!-- wp:column {"width":"40%"} --><div class="wp-block-column" style="flex-basis:40%"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} --><div class="wp-block-group"><!-- wp:site-logo {"width":42,"shouldSyncIcon":false} /--><!-- wp:site-title {"level":0,"textColor":"white"} /--></div><!-- /wp:group --><!-- wp:paragraph {"textColor":"slate","fontSize":"sm"} --><p class="has-slate-color has-text-color has-sm-font-size">Independent technology engineering for organisations that value dependable systems and straight answers.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"width":"20%"} --><div class="wp-block-column" style="flex-basis:20%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Explore</p><!-- /wp:paragraph --><!-- wp:navigation {"textColor":"white","overlayMenu":"never","layout":{"type":"flex","orientation":"vertical"}} /--></div><!-- /wp:column -->
<!-- wp:column {"width":"20%"} --><div class="wp-block-column" style="flex-basis:20%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Contact</p><!-- /wp:paragraph --><!-- wp:paragraph {"textColor":"white","fontSize":"sm"} --><p class="has-white-color has-text-color has-sm-font-size"><a href="mailto:hello@example.com">hello@example.com</a><br><a href="tel:+440000000000">+44 (0) 0000 000000</a></p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"width":"20%"} --><div class="wp-block-column" style="flex-basis:20%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Company</p><!-- /wp:paragraph --><!-- wp:paragraph {"textColor":"slate","fontSize":"sm"} --><p class="has-slate-color has-text-color has-sm-font-size">Rismor Technologies Ltd<br>United Kingdom<br>Company information can be edited here.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:group {"className":"rismor-footer-bottom","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"},"padding":{"top":"var:preset|spacing|30"}}},"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group rismor-footer-bottom" style="margin-top:var(--wp--preset--spacing--50);padding-top:var(--wp--preset--spacing--30)"><!-- wp:paragraph {"textColor":"slate","fontSize":"xs"} --><p class="has-slate-color has-text-color has-xs-font-size">© Rismor Technologies Ltd</p><!-- /wp:paragraph --><!-- wp:paragraph {"textColor":"slate","fontSize":"xs"} --><p class="has-slate-color has-text-color has-xs-font-size"><a href="#">Privacy</a> · <a href="#">Cookies</a> · <a href="#">Terms</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->