<?php
/**
 * Title: Technical grid hero
 * Slug: rismor/hero-technical-grid
 * Categories: rismor-hero
 * Description: White engineering-led hero with a native-block technical grid and annotation rail.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","className":"rismor-technical-hero","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-technical-hero" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:columns {"align":"wide","verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center","width":"46%"} --><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:46%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Technology built to work</p><!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"fontSize":"4xl"} --><h1 class="wp-block-heading has-4-xl-font-size">Complex underneath. Simple where it matters.</h1><!-- /wp:heading -->
<!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">We engineer dependable technology foundations, then make them understandable, supportable and useful to the people relying on them.</p><!-- /wp:paragraph -->
<!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-rismor-arrow"} --><div class="wp-block-button is-style-rismor-arrow"><a class="wp-block-button__link wp-element-button" href="#">Explore capabilities</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">View projects</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"center","width":"54%"} --><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:54%"><!-- wp:group {"className":"rismor-system-map","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-system-map"><!-- wp:paragraph {"className":"rismor-map-node rismor-map-node-a"} --><p class="rismor-map-node rismor-map-node-a">Identity</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"rismor-map-node rismor-map-node-b"} --><p class="rismor-map-node rismor-map-node-b">Cloud</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"rismor-map-node rismor-map-node-c"} --><p class="rismor-map-node rismor-map-node-c">Backup</p><!-- /wp:paragraph --><!-- wp:paragraph {"className":"rismor-map-node rismor-map-node-d"} --><p class="rismor-map-node rismor-map-node-d">Network</p><!-- /wp:paragraph --><!-- wp:group {"className":"rismor-map-core","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-map-core"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Rismor</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Designed as one system</h3><!-- /wp:heading --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-annotation-rail","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group rismor-annotation-rail"><!-- wp:paragraph {"fontSize":"xs"} --><p class="has-xs-font-size"><strong>01</strong> Resilient by design</p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"xs"} --><p class="has-xs-font-size"><strong>02</strong> Secure by default</p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"xs"} --><p class="has-xs-font-size"><strong>03</strong> Supportable in practice</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->