<?php
/**
 * Title: Industry pathways
 * Slug: rismor/industries-pathways
 * Categories: rismor-content
 * Description: Editorial sector pathways focused on business context instead of generic industry cards.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"mist","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-mist-background-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","className":"rismor-industry-pathways","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide rismor-industry-pathways"><!-- wp:columns {"verticalAlignment":"bottom"} --><div class="wp-block-columns are-vertically-aligned-bottom"><!-- wp:column {"verticalAlignment":"bottom","width":"48%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:48%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Where we fit</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Different sectors. Similar pressure on the technology underneath.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"bottom","width":"52%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:52%"><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">Frame sectors around the operational environment and risks that matter to them rather than changing the logo on the same service list.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"className":"rismor-industry-grid","style":{"spacing":{"margin":{"top":"var:preset|spacing|60"},"blockGap":{"left":"var:preset|spacing|40"}}}} --><div class="wp-block-columns rismor-industry-grid" style="margin-top:var(--wp--preset--spacing--60)"><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">01</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Professional services</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Secure collaboration, identity, resilient data and technology that stays out of the way of billable work.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore sector →</a></p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">02</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Manufacturing</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Operational continuity, infrastructure lifecycle, network separation and recoverability around production-critical systems.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore sector →</a></p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">03</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Education &amp; charities</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Strong controls and dependable services without enterprise complexity becoming an operational burden.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore sector →</a></p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">04</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Growing businesses</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Build the foundations properly before ad-hoc accounts, devices, files and suppliers become tomorrow's migration project.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore sector →</a></p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group --></div><!-- /wp:group -->