<?php
/**
 * Title: Dynamic insight index
 * Slug: rismor/insights-query
 * Categories: rismor-content
 * Description: Native Query Loop for automatically listing the latest articles in an editorial layout.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:group {"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"bottom"}} --><div class="wp-block-group"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Latest insight</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Technical thinking, automatically kept current.</h2><!-- /wp:heading --></div><!-- /wp:group --><!-- wp:paragraph --><p><a href="#">Browse all insight →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:query {"queryId":21,"query":{"perPage":4,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"exclude","inherit":false},"align":"wide","className":"rismor-query-editorial","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} --><div class="wp-block-query alignwide rismor-query-editorial" style="margin-top:var(--wp--preset--spacing--50)"><!-- wp:post-template {"layout":{"type":"grid","columnCount":2}} --><!-- wp:group {"className":"rismor-query-item","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"}}},"layout":{"type":"constrained"}} --><div class="wp-block-group rismor-query-item" style="padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40)"><!-- wp:post-terms {"term":"category","className":"rismor-eyebrow","textColor":"blue","fontSize":"xs"} /--><!-- wp:post-title {"isLink":true,"fontSize":"2xl"} /--><!-- wp:post-excerpt {"moreText":"Read article →","excerptLength":24} /--><!-- wp:post-date {"fontSize":"xs"} /--></div><!-- /wp:group --><!-- /wp:post-template --><!-- wp:query-pagination {"layout":{"type":"flex","justifyContent":"space-between"}} --><!-- wp:query-pagination-previous /--><!-- wp:query-pagination-numbers /--><!-- wp:query-pagination-next /--><!-- /wp:query-pagination --><!-- wp:query-no-results --><!-- wp:paragraph --><p>No insight articles have been published yet.</p><!-- /wp:paragraph --><!-- /wp:query-no-results --></div><!-- /wp:query --></div><!-- /wp:group --></div><!-- /wp:group -->