<?php
/**
 * Title: Featured insights editorial
 * Slug: rismor/insights-feature
 * Categories: rismor-content
 * Description: Editorial article feature with one lead story and two compact supporting stories.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"mist","className":"rismor-insights","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-insights has-mist-background-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:group {"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"bottom"}} --><div class="wp-block-group"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Insight</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Useful thinking from the workbench.</h2><!-- /wp:heading --></div><!-- /wp:group --><!-- wp:paragraph --><p><a href="#">View all insights →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:columns {"className":"rismor-insight-grid","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"},"blockGap":{"left":"var:preset|spacing|50"}}}} --><div class="wp-block-columns rismor-insight-grid" style="margin-top:var(--wp--preset--spacing--50)"><!-- wp:column {"width":"62%"} --><div class="wp-block-column" style="flex-basis:62%"><!-- wp:cover {"dimRatio":0,"overlayColor":"white","minHeight":430,"className":"rismor-insight-canvas"} --><div class="wp-block-cover rismor-insight-canvas" style="min-height:430px"><span aria-hidden="true" class="wp-block-cover__background has-white-background-color has-background-dim-0 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"rismor-insight-copy","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-insight-copy"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Guide · Microsoft 365</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"2xl"} --><h3 class="wp-block-heading has-2-xl-font-size">External sharing without turning collaboration into a security problem.</h3><!-- /wp:heading --><!-- wp:paragraph --><p>A practical guide to balancing usability, identity controls and external access.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Read the guide →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div><!-- /wp:cover --></div><!-- /wp:column -->
<!-- wp:column {"width":"38%"} --><div class="wp-block-column" style="flex-basis:38%"><!-- wp:group {"className":"rismor-insight-stack","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-insight-stack"><!-- wp:group {"className":"rismor-insight-item","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-insight-item"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Resilience</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Why immutable backups are not the same as unreachable backups.</h3><!-- /wp:heading --><!-- wp:paragraph --><p><a href="#">Read article →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-insight-item","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-insight-item"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Infrastructure</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">When upgrading the platform is cheaper than nursing the old one.</h3><!-- /wp:heading --><!-- wp:paragraph --><p><a href="#">Read article →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group --></div><!-- /wp:group -->