<?php
/**
 * Title: Metrics and outcomes
 * Slug: rismor/metrics-outcomes
 * Categories: rismor-proof
 * Description: Large editorial metrics with supporting outcome statements.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"ink","textColor":"white","className":"rismor-metrics","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-metrics has-white-color has-ink-background-color has-text-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:columns {"verticalAlignment":"bottom"} --><div class="wp-block-columns are-vertically-aligned-bottom"><!-- wp:column {"verticalAlignment":"bottom","width":"42%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:42%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">Outcome, not activity</p><!-- /wp:paragraph --><!-- wp:heading {"textColor":"white","fontSize":"3xl"} --><h2 class="wp-block-heading has-white-color has-text-color has-3-xl-font-size">Show the difference the work made.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"bottom","width":"58%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:58%"><!-- wp:paragraph {"textColor":"white","fontSize":"lg"} --><p class="has-white-color has-text-color has-lg-font-size">Replace these starter figures with measured service, recovery, cost, delivery or risk outcomes from a real engagement.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"className":"rismor-metric-grid","style":{"spacing":{"margin":{"top":"var:preset|spacing|60"},"blockGap":{"left":"var:preset|spacing|50"}}}} --><div class="wp-block-columns rismor-metric-grid" style="margin-top:var(--wp--preset--spacing--60)"><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"rismor-metric-value","textColor":"cyan"} --><p class="rismor-metric-value has-cyan-color has-text-color">4×</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"textColor":"white","fontSize":"xl"} --><h3 class="wp-block-heading has-white-color has-text-color has-xl-font-size">Faster recovery</h3><!-- /wp:heading --><!-- wp:paragraph {"textColor":"white","fontSize":"sm"} --><p class="has-white-color has-text-color has-sm-font-size">Example outcome statement with enough context to make the number meaningful.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"rismor-metric-value","textColor":"cyan"} --><p class="rismor-metric-value has-cyan-color has-text-color">0</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"textColor":"white","fontSize":"xl"} --><h3 class="wp-block-heading has-white-color has-text-color has-xl-font-size">Reachable backup deletions</h3><!-- /wp:heading --><!-- wp:paragraph {"textColor":"white","fontSize":"sm"} --><p class="has-white-color has-text-color has-sm-font-size">Example resilience metric that communicates architecture rather than marketing fluff.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"rismor-metric-value","textColor":"cyan"} --><p class="rismor-metric-value has-cyan-color has-text-color">99.9%</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"textColor":"white","fontSize":"xl"} --><h3 class="wp-block-heading has-white-color has-text-color has-xl-font-size">Service availability</h3><!-- /wp:heading --><!-- wp:paragraph {"textColor":"white","fontSize":"sm"} --><p class="has-white-color has-text-color has-sm-font-size">Use only where the figure can be evidenced and explained on the associated case study.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group --></div><!-- /wp:group -->