<?php
/**
 * Title: Pricing comparison
 * Slug: rismor/pricing-comparison
 * Categories: rismor-conversion
 * Description: Clean comparison table for retainers, service levels or packages without SaaS-style pricing cards.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","className":"rismor-pricing","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-pricing" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:columns {"verticalAlignment":"bottom"} --><div class="wp-block-columns are-vertically-aligned-bottom"><!-- wp:column {"verticalAlignment":"bottom","width":"50%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:50%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Ways to work together</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Clear choices without hiding the detail.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"bottom","width":"50%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:50%"><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">This can be used for support plans, consultancy models or any comparison where the differences matter more than a flashy price box.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:table {"className":"rismor-comparison-table","style":{"spacing":{"margin":{"top":"var:preset|spacing|60"}}}} --><figure class="wp-block-table rismor-comparison-table" style="margin-top:var(--wp--preset--spacing--60)"><table><thead><tr><th> </th><th>Project</th><th>Partner</th><th>Managed</th></tr></thead><tbody><tr><td><strong>Best for</strong></td><td>Defined outcomes</td><td>Ongoing access to expertise</td><td>Operational ownership</td></tr><tr><td><strong>Discovery</strong></td><td>Included</td><td>Included</td><td>Included</td></tr><tr><td><strong>Delivery</strong></td><td>Scoped project</td><td>Flexible consultancy</td><td>Managed service</td></tr><tr><td><strong>Documentation</strong></td><td>Yes</td><td>Yes</td><td>Yes</td></tr><tr><td><strong>Review cadence</strong></td><td>At milestones</td><td>Agreed cadence</td><td>Service reviews</td></tr><tr><td><strong>Commercial model</strong></td><td>Quote / block</td><td>Retainer / block</td><td>Monthly</td></tr></tbody></table></figure><!-- /wp:table -->
<!-- wp:buttons {"style":{"spacing":{"margin":{"top":"var:preset|spacing|40"}}}} --><div class="wp-block-buttons" style="margin-top:var(--wp--preset--spacing--40)"><!-- wp:button {"className":"is-style-rismor-arrow"} --><div class="wp-block-button is-style-rismor-arrow"><a class="wp-block-button__link wp-element-button" href="#">Discuss the right model</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group -->