<?php
/**
 * Title: Process rail
 * Slug: rismor/process-rail
 * Categories: rismor-content
 * Description: Five-stage process presented as a continuous engineering rail.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","className":"rismor-process","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-process" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:columns {"verticalAlignment":"bottom"} --><div class="wp-block-columns are-vertically-aligned-bottom"><!-- wp:column {"verticalAlignment":"bottom","width":"52%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:52%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">How we work</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Enough process to be dependable. Never enough to get in the way.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"bottom","width":"48%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:48%"><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">A straightforward route from understanding the problem to proving the result and supporting what comes next.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"className":"rismor-process-rail","style":{"spacing":{"margin":{"top":"var:preset|spacing|60"},"blockGap":{"left":"0"}}}} --><div class="wp-block-columns rismor-process-rail" style="margin-top:var(--wp--preset--spacing--60)"><!-- wp:column {"className":"rismor-process-step"} --><div class="wp-block-column rismor-process-step"><!-- wp:paragraph {"className":"rismor-process-number","textColor":"blue"} --><p class="rismor-process-number has-blue-color has-text-color">01</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Understand</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size">Context, constraints, priorities and what success actually means.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"className":"rismor-process-step"} --><div class="wp-block-column rismor-process-step"><!-- wp:paragraph {"className":"rismor-process-number","textColor":"blue"} --><p class="rismor-process-number has-blue-color has-text-color">02</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Design</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size">Choose the simplest architecture that genuinely solves the requirement.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"className":"rismor-process-step"} --><div class="wp-block-column rismor-process-step"><!-- wp:paragraph {"className":"rismor-process-number","textColor":"blue"} --><p class="rismor-process-number has-blue-color has-text-color">03</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Build</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size">Implement carefully, document decisions and avoid avoidable complexity.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"className":"rismor-process-step"} --><div class="wp-block-column rismor-process-step"><!-- wp:paragraph {"className":"rismor-process-number","textColor":"blue"} --><p class="rismor-process-number has-blue-color has-text-color">04</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Prove</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size">Test the important paths, validate recovery and demonstrate the outcome.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column {"className":"rismor-process-step"} --><div class="wp-block-column rismor-process-step"><!-- wp:paragraph {"className":"rismor-process-number","textColor":"blue"} --><p class="rismor-process-number has-blue-color has-text-color">05</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Support</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size">Stay close enough to improve the system as the business changes.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group --></div><!-- /wp:group -->