<?php
/**
 * Title: Asymmetric project showcase
 * Slug: rismor/projects-asymmetric
 * Categories: rismor-projects
 * Description: Large staggered project features with different proportions and editable cover media.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"mist","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-mist-background-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide"><!-- wp:group {"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"bottom"}} --><div class="wp-block-group"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Selected work</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Different problems need different answers.</h2><!-- /wp:heading --></div><!-- /wp:group --><!-- wp:paragraph --><p><a href="#">View all projects →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:columns {"className":"rismor-project-pair rismor-project-pair-a","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"},"blockGap":{"left":"var:preset|spacing|50"}}}} --><div class="wp-block-columns rismor-project-pair rismor-project-pair-a" style="margin-top:var(--wp--preset--spacing--50)"><!-- wp:column {"width":"66%"} --><div class="wp-block-column" style="flex-basis:66%"><!-- wp:cover {"dimRatio":20,"overlayColor":"ink","minHeight":620,"className":"rismor-project-cover"} --><div class="wp-block-cover rismor-project-cover" style="min-height:620px"><span aria-hidden="true" class="wp-block-cover__background has-ink-background-color has-background-dim-20 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"rismor-cover-copy","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-cover-copy"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">01 · Platform engineering</p><!-- /wp:paragraph --><!-- wp:heading {"textColor":"white","fontSize":"2xl"} --><h2 class="wp-block-heading has-white-color has-text-color has-2-xl-font-size">A secure development environment built for rapid experimentation.</h2><!-- /wp:heading --><!-- wp:paragraph {"textColor":"white"} --><p class="has-white-color has-text-color"><a href="#">View project →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div></div><!-- /wp:cover --></div><!-- /wp:column -->
<!-- wp:column {"width":"34%","style":{"spacing":{"padding":{"top":"var:preset|spacing|70"}}}} --><div class="wp-block-column" style="padding-top:var(--wp--preset--spacing--70);flex-basis:34%"><!-- wp:cover {"dimRatio":10,"overlayColor":"navy","minHeight":430,"className":"rismor-project-cover"} --><div class="wp-block-cover rismor-project-cover" style="min-height:430px"><span aria-hidden="true" class="wp-block-cover__background has-navy-background-color has-background-dim-10 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"rismor-cover-copy","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-cover-copy"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">02 · Resilience</p><!-- /wp:paragraph --><!-- wp:heading {"textColor":"white","fontSize":"xl"} --><h2 class="wp-block-heading has-white-color has-text-color has-xl-font-size">Backup architecture without a reachable deletion path.</h2><!-- /wp:heading --></div><!-- /wp:group --></div></div><!-- /wp:cover --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"className":"rismor-project-pair rismor-project-pair-b","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"},"blockGap":{"left":"var:preset|spacing|50"}}}} --><div class="wp-block-columns rismor-project-pair rismor-project-pair-b" style="margin-top:var(--wp--preset--spacing--50)"><!-- wp:column {"width":"42%"} --><div class="wp-block-column" style="flex-basis:42%"><!-- wp:cover {"dimRatio":15,"overlayColor":"ink","minHeight":470,"className":"rismor-project-cover"} --><div class="wp-block-cover rismor-project-cover" style="min-height:470px"><span aria-hidden="true" class="wp-block-cover__background has-ink-background-color has-background-dim-15 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"rismor-cover-copy","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-cover-copy"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">03 · Collaboration</p><!-- /wp:paragraph --><!-- wp:heading {"textColor":"white","fontSize":"xl"} --><h2 class="wp-block-heading has-white-color has-text-color has-xl-font-size">External collaboration without destroying usability.</h2><!-- /wp:heading --></div><!-- /wp:group --></div></div><!-- /wp:cover --></div><!-- /wp:column -->
<!-- wp:column {"width":"58%","style":{"spacing":{"padding":{"top":"var:preset|spacing|30"}}}} --><div class="wp-block-column" style="padding-top:var(--wp--preset--spacing--30);flex-basis:58%"><!-- wp:cover {"dimRatio":15,"overlayColor":"navy","minHeight":560,"className":"rismor-project-cover"} --><div class="wp-block-cover rismor-project-cover" style="min-height:560px"><span aria-hidden="true" class="wp-block-cover__background has-navy-background-color has-background-dim-15 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"rismor-cover-copy","layout":{"type":"constrained"}} --><div class="wp-block-group rismor-cover-copy"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"cyan"} --><p class="rismor-eyebrow has-cyan-color has-text-color">04 · Infrastructure</p><!-- /wp:paragraph --><!-- wp:heading {"textColor":"white","fontSize":"2xl"} --><h2 class="wp-block-heading has-white-color has-text-color has-2-xl-font-size">Modernising infrastructure without stopping the business.</h2><!-- /wp:heading --></div><!-- /wp:group --></div></div><!-- /wp:cover --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group --></div><!-- /wp:group -->