<?php
/**
 * Title: Client proof ledger
 * Slug: rismor/proof-client-ledger
 * Categories: rismor-proof
 * Description: Minimal client and credibility section using an editorial ledger rather than a logo carousel.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"align":"wide","className":"rismor-proof-ledger","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide rismor-proof-ledger"><!-- wp:columns {"verticalAlignment":"bottom"} --><div class="wp-block-columns are-vertically-aligned-bottom"><!-- wp:column {"verticalAlignment":"bottom","width":"52%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:52%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Trusted in the real world</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Long-term relationships beat impressive sales decks.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"bottom","width":"48%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:48%"><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">Use this space for customers, accreditations, measurable proof or the reasons organisations keep working with you.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:group {"className":"rismor-ledger-rows","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} --><div class="wp-block-group rismor-ledger-rows" style="margin-top:var(--wp--preset--spacing--50)"><!-- wp:group {"className":"rismor-ledger-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group rismor-ledger-row"><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Monton</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Technology partner</p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size">Managed infrastructure · Microsoft 365 · Support</p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-ledger-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group rismor-ledger-row"><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">ABM</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Technology partner</p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size">Cloud · Security · Business continuity</p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-ledger-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} --><div class="wp-block-group rismor-ledger-row"><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Quantum</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Technology partner</p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size">Infrastructure · Backup · Collaboration</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->