<?php
/**
 * Title: Editorial services index
 * Slug: rismor/services-editorial
 * Categories: rismor-content
 * Description: Large numbered service index with expandable editorial feel and no card grid.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"white","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-white-background-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","className":"rismor-services-editorial","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide rismor-services-editorial"><!-- wp:columns {"verticalAlignment":"bottom"} --><div class="wp-block-columns are-vertically-aligned-bottom"><!-- wp:column {"verticalAlignment":"bottom","width":"42%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:42%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Capabilities</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">One technology partner. Six useful disciplines.</h2><!-- /wp:heading --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"bottom","width":"58%"} --><div class="wp-block-column is-vertically-aligned-bottom" style="flex-basis:58%"><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">Use this section to explain breadth without reducing complex services to six identical icon boxes.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:group {"className":"rismor-service-list","style":{"spacing":{"margin":{"top":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} --><div class="wp-block-group rismor-service-list" style="margin-top:var(--wp--preset--spacing--60)">
<!-- wp:group {"className":"rismor-service-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"center"}} --><div class="wp-block-group rismor-service-row"><!-- wp:paragraph {"className":"rismor-service-index","textColor":"blue"} --><p class="rismor-service-index has-blue-color has-text-color">01</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"2xl"} --><h3 class="wp-block-heading has-2-xl-font-size">Cloud &amp; Microsoft 365</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Identity, collaboration, migrations and secure modern workplace design.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-service-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"center"}} --><div class="wp-block-group rismor-service-row"><!-- wp:paragraph {"className":"rismor-service-index","textColor":"blue"} --><p class="rismor-service-index has-blue-color has-text-color">02</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"2xl"} --><h3 class="wp-block-heading has-2-xl-font-size">Cyber resilience</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Backup, recovery and architecture built to survive the incidents that matter.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-service-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"center"}} --><div class="wp-block-group rismor-service-row"><!-- wp:paragraph {"className":"rismor-service-index","textColor":"blue"} --><p class="rismor-service-index has-blue-color has-text-color">03</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"2xl"} --><h3 class="wp-block-heading has-2-xl-font-size">Infrastructure</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Servers, virtualisation, storage, networking and dependable platform foundations.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-service-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"center"}} --><div class="wp-block-group rismor-service-row"><!-- wp:paragraph {"className":"rismor-service-index","textColor":"blue"} --><p class="rismor-service-index has-blue-color has-text-color">04</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"2xl"} --><h3 class="wp-block-heading has-2-xl-font-size">Cyber security</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Practical risk reduction, vulnerability management, hardening and monitoring.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-service-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"center"}} --><div class="wp-block-group rismor-service-row"><!-- wp:paragraph {"className":"rismor-service-index","textColor":"blue"} --><p class="rismor-service-index has-blue-color has-text-color">05</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"2xl"} --><h3 class="wp-block-heading has-2-xl-font-size">Web &amp; hosting</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Fast websites, hosting, DNS and edge protection without unnecessary platform baggage.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"rismor-service-row","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between","verticalAlignment":"center"}} --><div class="wp-block-group rismor-service-row"><!-- wp:paragraph {"className":"rismor-service-index","textColor":"blue"} --><p class="rismor-service-index has-blue-color has-text-color">06</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"2xl"} --><h3 class="wp-block-heading has-2-xl-font-size">Technical projects</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Automation, integration and bespoke engineering for unusual or awkward requirements.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Explore →</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
</div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->