<?php
/**
 * Title: Editorial team profile
 * Slug: rismor/team-editorial
 * Categories: rismor-content
 * Description: Human team introduction with one large profile and compact supporting roles.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","backgroundColor":"mist","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-mist-background-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:group {"align":"wide","className":"rismor-team-editorial","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide rismor-team-editorial"><!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns"><!-- wp:column {"width":"48%"} --><div class="wp-block-column" style="flex-basis:48%"><!-- wp:cover {"dimRatio":0,"overlayColor":"white","minHeight":600,"className":"rismor-profile-media"} --><div class="wp-block-cover rismor-profile-media" style="min-height:600px"><span aria-hidden="true" class="wp-block-cover__background has-white-background-color has-background-dim-0 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","className":"rismor-eyebrow","textColor":"slate"} --><p class="has-text-align-center rismor-eyebrow has-slate-color has-text-color">Replace with portrait or working image</p><!-- /wp:paragraph --></div></div><!-- /wp:cover --></div><!-- /wp:column -->
<!-- wp:column {"width":"52%"} --><div class="wp-block-column" style="flex-basis:52%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Who you are dealing with</p><!-- /wp:paragraph --><!-- wp:heading {"fontSize":"3xl"} --><h2 class="wp-block-heading has-3-xl-font-size">Senior engineering without the layers.</h2><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"lg"} --><p class="has-lg-font-size">Use this section to explain the people, judgement and experience behind the company rather than pretending a small expert team is a giant anonymous operation.</p><!-- /wp:paragraph --><!-- wp:separator --><hr class="wp-block-separator has-alpha-channel-opacity"/><!-- /wp:separator --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Ian Morris</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Chief Technical Officer</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Infrastructure, cloud, resilience, security and the awkward technical projects that do not fit neatly into a catalogue.</p><!-- /wp:paragraph --><!-- wp:group {"className":"rismor-team-facts","layout":{"type":"flex","flexWrap":"wrap"}} --><div class="wp-block-group rismor-team-facts"><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size"><strong>Focus</strong><br>Architecture &amp; delivery</p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size"><strong>Approach</strong><br>Practical, direct, accountable</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group --></div><!-- /wp:group -->