<?php
/**
 * Title: Split testimonial story
 * Slug: rismor/testimonial-split
 * Categories: rismor-proof
 * Description: Large testimonial with supporting relationship context and editable proof points.
 * Viewport Width: 1440
 */
?>
<!-- wp:group {"align":"full","className":"rismor-testimonial-split","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rismor-testimonial-split" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns alignwide"><!-- wp:column {"width":"66%"} --><div class="wp-block-column" style="flex-basis:66%"><!-- wp:paragraph {"className":"rismor-quote-mark","textColor":"cyan"} --><p class="rismor-quote-mark has-cyan-color has-text-color">“</p><!-- /wp:paragraph --><!-- wp:quote {"className":"rismor-large-quote"} --><blockquote class="wp-block-quote rismor-large-quote"><!-- wp:paragraph {"fontSize":"3xl"} --><p class="has-3-xl-font-size">Rismor work as an integral part of our business - proactive, helpful and available when we need them.</p><!-- /wp:paragraph --></blockquote><!-- /wp:quote --><!-- wp:group {"layout":{"type":"flex","flexWrap":"wrap"}} --><div class="wp-block-group"><!-- wp:paragraph --><p><strong>Gary Newton</strong><br>Director, Monton</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Read the full story →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column {"width":"34%","className":"rismor-testimonial-context"} --><div class="wp-block-column rismor-testimonial-context" style="flex-basis:34%"><!-- wp:paragraph {"className":"rismor-eyebrow","textColor":"blue"} --><p class="rismor-eyebrow has-blue-color has-text-color">Relationship</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"fontSize":"xl"} --><h3 class="wp-block-heading has-xl-font-size">Technology partner</h3><!-- /wp:heading --><!-- wp:separator --><hr class="wp-block-separator has-alpha-channel-opacity"/><!-- /wp:separator --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size"><strong>Areas</strong><br>Infrastructure<br>Microsoft 365<br>Business continuity</p><!-- /wp:paragraph --><!-- wp:paragraph {"fontSize":"sm"} --><p class="has-sm-font-size"><strong>Working style</strong><br>Ongoing partnership</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->